# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_del(object):
    def setupUi(self, Dialog_del):
        Dialog_del.setObjectName("Dialog_del")
        Dialog_del.resize(555, 263)
        self.label = QtWidgets.QLabel(Dialog_del)
        self.label.setGeometry(QtCore.QRect(9, 45, 63, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_del)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 63, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_del_del = QtWidgets.QPushButton(Dialog_del)
        self.pushButton_del_del.setGeometry(QtCore.QRect(10, 190, 241, 40))
        self.pushButton_del_del.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_del_del.setObjectName("pushButton_del_del")
        self.pushButton_del_cancel = QtWidgets.QPushButton(Dialog_del)
        self.pushButton_del_cancel.setGeometry(QtCore.QRect(290, 190, 241, 40))
        self.pushButton_del_cancel.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_del_cancel.setObjectName("pushButton_del_cancel")
        self.textBrowser_del_name = QtWidgets.QTextBrowser(Dialog_del)
        self.textBrowser_del_name.setGeometry(QtCore.QRect(70, 40, 461, 40))
        self.textBrowser_del_name.setMinimumSize(QtCore.QSize(0, 40))
        self.textBrowser_del_name.setObjectName("textBrowser_del_name")
        self.textBrowser_del_remark = QtWidgets.QTextBrowser(Dialog_del)
        self.textBrowser_del_remark.setGeometry(QtCore.QRect(70, 110, 461, 40))
        self.textBrowser_del_remark.setMinimumSize(QtCore.QSize(0, 40))
        self.textBrowser_del_remark.setObjectName("textBrowser_del_remark")

        self.retranslateUi(Dialog_del)
        QtCore.QMetaObject.connectSlotsByName(Dialog_del)

    def retranslateUi(self, Dialog_del):
        _translate = QtCore.QCoreApplication.translate
        Dialog_del.setWindowTitle(_translate("Dialog_del", "Dialog"))
        self.label.setText(_translate("Dialog_del", "名称："))
        self.label_2.setText(_translate("Dialog_del", "备注："))
        self.pushButton_del_del.setText(_translate("Dialog_del", "删除"))
        self.pushButton_del_cancel.setText(_translate("Dialog_del", "取消"))
