# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_load(object):
    def setupUi(self, Dialog_load):
        Dialog_load.setObjectName("Dialog_load")
        Dialog_load.resize(555, 263)
        self.label = QtWidgets.QLabel(Dialog_load)
        self.label.setGeometry(QtCore.QRect(9, 45, 63, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_load)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 63, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_load_load = QtWidgets.QPushButton(Dialog_load)
        self.pushButton_load_load.setGeometry(QtCore.QRect(10, 190, 241, 40))
        self.pushButton_load_load.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_load_load.setObjectName("pushButton_load_load")
        self.pushButton_load_cancel = QtWidgets.QPushButton(Dialog_load)
        self.pushButton_load_cancel.setGeometry(QtCore.QRect(290, 190, 241, 40))
        self.pushButton_load_cancel.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_load_cancel.setObjectName("pushButton_load_cancel")
        self.textBrowser_load_name = QtWidgets.QTextBrowser(Dialog_load)
        self.textBrowser_load_name.setGeometry(QtCore.QRect(70, 40, 461, 40))
        self.textBrowser_load_name.setMinimumSize(QtCore.QSize(0, 40))
        self.textBrowser_load_name.setObjectName("textBrowser_load_name")
        self.textBrowser_load_remark = QtWidgets.QTextBrowser(Dialog_load)
        self.textBrowser_load_remark.setGeometry(QtCore.QRect(70, 110, 461, 40))
        self.textBrowser_load_remark.setMinimumSize(QtCore.QSize(0, 40))
        self.textBrowser_load_remark.setObjectName("textBrowser_load_remark")

        self.retranslateUi(Dialog_load)
        QtCore.QMetaObject.connectSlotsByName(Dialog_load)

    def retranslateUi(self, Dialog_load):
        _translate = QtCore.QCoreApplication.translate
        Dialog_load.setWindowTitle(_translate("Dialog_load", "Dialog"))
        self.label.setText(_translate("Dialog_load", "名称："))
        self.label_2.setText(_translate("Dialog_load", "备注："))
        self.pushButton_load_load.setText(_translate("Dialog_load", "加载"))
        self.pushButton_load_cancel.setText(_translate("Dialog_load", "取消"))
