# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saveload.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_saveload(object):
    def setupUi(self, Dialog_saveload):
        Dialog_saveload.setObjectName("Dialog_saveload")
        Dialog_saveload.resize(997, 612)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_saveload)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_saveload = QtWidgets.QTableWidget(Dialog_saveload)
        self.tableWidget_saveload.setAlternatingRowColors(True)
        self.tableWidget_saveload.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_saveload.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_saveload.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_saveload.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_saveload.setRowCount(20)
        self.tableWidget_saveload.setColumnCount(6)
        self.tableWidget_saveload.setObjectName("tableWidget_saveload")
        self.tableWidget_saveload.horizontalHeader().setDefaultSectionSize(150)
        self.gridLayout.addWidget(self.tableWidget_saveload, 0, 0, 1, 4)
        self.pushButton_saveload_save = QtWidgets.QPushButton(Dialog_saveload)
        self.pushButton_saveload_save.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_saveload_save.setObjectName("pushButton_saveload_save")
        self.gridLayout.addWidget(self.pushButton_saveload_save, 1, 0, 1, 1)
        self.pushButton_saveload_load = QtWidgets.QPushButton(Dialog_saveload)
        self.pushButton_saveload_load.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_saveload_load.setObjectName("pushButton_saveload_load")
        self.gridLayout.addWidget(self.pushButton_saveload_load, 1, 1, 1, 1)
        self.pushButton_saveload_del = QtWidgets.QPushButton(Dialog_saveload)
        self.pushButton_saveload_del.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_saveload_del.setObjectName("pushButton_saveload_del")
        self.gridLayout.addWidget(self.pushButton_saveload_del, 1, 2, 1, 1)
        self.pushButton_saveload_cancel = QtWidgets.QPushButton(Dialog_saveload)
        self.pushButton_saveload_cancel.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_saveload_cancel.setObjectName("pushButton_saveload_cancel")
        self.gridLayout.addWidget(self.pushButton_saveload_cancel, 1, 3, 1, 1)

        self.retranslateUi(Dialog_saveload)
        QtCore.QMetaObject.connectSlotsByName(Dialog_saveload)

    def retranslateUi(self, Dialog_saveload):
        _translate = QtCore.QCoreApplication.translate
        Dialog_saveload.setWindowTitle(_translate("Dialog_saveload", "Dialog"))
        self.pushButton_saveload_save.setText(_translate("Dialog_saveload", "保存"))
        self.pushButton_saveload_load.setText(_translate("Dialog_saveload", "加载"))
        self.pushButton_saveload_del.setText(_translate("Dialog_saveload", "删除"))
        self.pushButton_saveload_cancel.setText(_translate("Dialog_saveload", "取消"))
