# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_save(object):
    def setupUi(self, Dialog_save):
        Dialog_save.setObjectName("Dialog_save")
        Dialog_save.resize(555, 258)
        self.lineEdit_save_name = QtWidgets.QLineEdit(Dialog_save)
        self.lineEdit_save_name.setGeometry(QtCore.QRect(70, 40, 461, 40))
        self.lineEdit_save_name.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_save_name.setFont(font)
        self.lineEdit_save_name.setObjectName("lineEdit_save_name")
        self.lineEdit_save_remark = QtWidgets.QLineEdit(Dialog_save)
        self.lineEdit_save_remark.setGeometry(QtCore.QRect(70, 110, 461, 40))
        self.lineEdit_save_remark.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_save_remark.setFont(font)
        self.lineEdit_save_remark.setObjectName("lineEdit_save_remark")
        self.label = QtWidgets.QLabel(Dialog_save)
        self.label.setGeometry(QtCore.QRect(9, 45, 63, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_save)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 63, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_save_save = QtWidgets.QPushButton(Dialog_save)
        self.pushButton_save_save.setGeometry(QtCore.QRect(10, 190, 241, 40))
        self.pushButton_save_save.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_save_save.setObjectName("pushButton_save_save")
        self.pushButton_save_cancel = QtWidgets.QPushButton(Dialog_save)
        self.pushButton_save_cancel.setGeometry(QtCore.QRect(290, 190, 241, 40))
        self.pushButton_save_cancel.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_save_cancel.setObjectName("pushButton_save_cancel")

        self.retranslateUi(Dialog_save)
        QtCore.QMetaObject.connectSlotsByName(Dialog_save)

    def retranslateUi(self, Dialog_save):
        _translate = QtCore.QCoreApplication.translate
        Dialog_save.setWindowTitle(_translate("Dialog_save", "Dialog"))
        self.label.setText(_translate("Dialog_save", "名称："))
        self.label_2.setText(_translate("Dialog_save", "备注："))
        self.pushButton_save_save.setText(_translate("Dialog_save", "保存"))
        self.pushButton_save_cancel.setText(_translate("Dialog_save", "取消"))
